# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Craft | Leadership
email: me@michaelrice.com
description: > # this means to ignore newlines until "baseurl:"
  A field guide for software engineering leaders who what to improve the craft
  of building software. More to come. Stay tuned.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://craftleadership.org" # the base hostname & protocol for your site
twitter_username: craftleadership
github_username:  craftleadership

# Build settings
markdown: kramdown
