title: Craft, Leadership
email: me@michaelrice.com
description: > # this means to ignore newlines until "baseurl:"
  A field guide for software engineering leaders who want to improve the craft
  of building software. More to come. Stay tuned, come back often, and get involved.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://craftleadership.org" # the base hostname & protocol for your site
twitter_username: craftleadership
github_username:  craftleadership

# Build settings
markdown: kramdown
